steps:
- name: node:19.3.0
  entrypoint: yarn
  args: ["install"]
- name: node:19.3.0
  entrypoint: yarn
  args: ["build", "--prod"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"